export const STATES = [
  "Maharashtra",
  "Delhi",
  "Karnataka",
  "Tamil Nadu",
  "Gujarat",
  "Rajasthan",
  "Telangana",
  "West Bengal",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Bihar",
  "Jharkhand",
  "Odisha",
  "Chandigarh",
  "Uttarakhand",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Assam",
  "Manipur",
];

export const BUSINESS_TYPES = [
  "Retail",
  "Service",
  "Manufacturing",
  "Software/IT",
  "E-commerce",
  "Education",
  "Healthcare",
  "Finance",
  "Construction",
  "Hospitality",
  "Logistics",
  "Real Estate",
  "Entertainment",
  "Agriculture",
  "Automobile",
  "Textiles",
  "Freelancer/Individual",
  "Other",
];

export const CITIES = [
  "Mumbai",
  "Pune",
  "Nagpur",
  "New Delhi",
  "Bangalore",
  "Mysore",
  "Mangalore",
  "Chennai",
  "Coimbatore",
  "Madurai",
  "Ahmedabad",
  "Surat",
  "Vadodara",
  "Jaipur",
  "Udaipur",
  "Jodhpur",
  "Hyderabad",
  "Warangal",
  "Kolkata",
  "Howrah",
  "Lucknow",
  "Kanpur",
  "Varanasi",
  "Bhopal",
  "Indore",
  "Patna",
  "Ranchi",
  "Bhubaneswar",
  "Chandigarh",
  "Dehradun",
  "Shimla",
  "Srinagar",
  "Guwahati",
  "Imphal",
];
